kind: pipeline
type: docker
name: default

steps:
  - name: 🧱 Build
    image: node:15
    commands:
      - yarn install --pure-lockfile
      - yarn generate

  - name: 📦 Deploy
    image: cschlosser/drone-ftps
    settings:
      hostname:
        from_secret: ftp_server
      ftp_username:
        from_secret: ftp_username
      ftp_password:
        from_secret: ftp_password
      verify: false
      exclude:
        - ^\.git/$
        - ^\.gitignore$
        - ^\.drone.yml$
      src_dir: /dist
    when:
      branch:
        - master
      event:
        - push
