kind: pipeline
type: docker
name: default

steps:
  - name: build 🧱
    image: node:15
    commands:
      - yarn install --pure-lockfile
      - yarn generate

  - name: deploy 📦
    image: cschlosser/drone-ftps
    environment:
      PLUGIN_HOSTNAME:
        from_secret: FTP_SERVER
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
      PLUGIN_VERIFY: false
      PLUGIN_SRC_DIR: /dist
    when:
      branch:
        - master
      event:
        - push
