name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install
      - name: Generate
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: generate
      - name: Deploy
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: deploy
