name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: install
      - name: Generate
        uses: CultureHQ/actions-yarn@v1.0.1
        with:
          args: generate    
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to
          FOLDER: dist # The folder the action should deploy
          CLEAN: false # Automatically remove deleted files from the deploy branch
